#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly=TRUE)
phase <- if(length(args)) normalizePath(args[1]) else normalizePath('.')
extra <- Sys.getenv('KIDNEY_R_LIB', '')
if(dir.exists(extra)) .libPaths(c(extra,.libPaths()))
library(limma)
read_mat <- function(name) as.matrix(read.delim(gzfile(file.path(phase,'01_sources',name)),row.names=1,check.names=FALSE))
fg <- read_mat('cy5_foreground.tsv.gz'); bg <- read_mat('cy5_background.tsv.gz')
stopifnot(identical(dimnames(fg),dimnames(bg)),all(is.finite(fg)),all(is.finite(bg)),ncol(fg)==71)
raw <- new('EListRaw',list(E=fg,Eb=bg))
corrected <- backgroundCorrect(raw,method='normexp',offset=50,verbose=FALSE)
normalized <- normalizeBetweenArrays(corrected,method='quantile')
stopifnot(all(is.finite(normalized$E)))
con <- gzfile(file.path(phase,'01_sources/cy5_normalized_log2.tsv.gz'),'wt')
write.table(data.frame(feature_key=rownames(normalized$E),normalized$E,check.names=FALSE),con,sep='\t',row.names=FALSE,quote=FALSE)
close(con)
writeLines(capture.output(sessionInfo()),file.path(phase,'09_qa/R_normalization_session.txt'))
write.table(data.frame(sample=colnames(fg),raw_median=apply(fg,2,median),normalized_median=apply(normalized$E,2,median),normalized_min=apply(normalized$E,2,min),normalized_max=apply(normalized$E,2,max)),file.path(phase,'02_audit/normalization_summary.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
cat('Normalized',nrow(fg),'features across',ncol(fg),'Cy5 kidney arrays with limma',as.character(packageVersion('limma')),'\n')
